### ISSUE TITLE
Eiger cannot run standalone

### ISSUE THREAD

**Issue by callumforrester** [dls-controls/tickit-devices#69]
All devices should be able to run as singleton graphs after https://github.com/dls-controls/tickit/pull/120
But trying this with the Eiger gives

Config:
```yaml
- type: tickit_devices.eiger.Eiger
  inputs: {}
  name: eiger
```

Error:
```shell
Traceback (most recent call last):
  File "/home/vid18871/projects/tickit-devices/venv/lib64/python3.9/site-packages/tickit/adapters/zeromq/push_adapter.py", line 93, in send_message_sequence
    await self.send_message(message)
  File "/home/vid18871/projects/tickit-devices/venv/lib64/python3.9/site-packages/tickit/adapters/zeromq/push_adapter.py", line 98, in send_message
    socket = await self._ensure_socket()
  File "/home/vid18871/projects/tickit-devices/venv/lib64/python3.9/site-packages/tickit/adapters/zeromq/push_adapter.py", line 104, in _ensure_socket
    async with self._socket_lock:
  File "/usr/lib64/python3.9/asyncio/locks.py", line 14, in __aenter__
    await self.acquire()
  File "/usr/lib64/python3.9/asyncio/locks.py", line 120, in acquire
    await fut
RuntimeError: Task <Task pending name='Task-9' coro=<ZeroMqPushAdapter.send_message_sequence_soon.<locals>.send_message_sequence() running at /home/vid18871/projects/tickit-devices/venv/lib64/python3.9/site-packages/tickit/adapters/zeromq/push_adapter.py:93>> got Future <Future pending> attached to a different loop
```

**Comment by callumforrester** [comment]
Local versioning issue, all resolved
